services:
  django:
    build: .
    container_name: django_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # Explicitly mount persistent data directories
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - ./logs:/app/logs
      - ./static:/app/static
    environment:
      - PYTHONUNBUFFERED=1